### PR TITLE
add starting_values as an argument

### PR DESCRIPTION
**Pull request by shuhoy**

### CODE REVIEW

**Comment by pabloduque0** [comment]
Hey @shuhoy ! Thanks for opening this.

I can add some of the changes you suggested if we see merit for them. Can you explain a bit the reasoning by passing custom starting values?

We are working around adding more flexibility around the boundaries, but I missing to see why you want to pass custom starting values for optimization. Are you looking for them to be based on a specific distribution? or are you running into unvalid starting values that lead to failed optimizations? If so, let me know so we can look into why that might be happening.

**Comment by shuhoy** [comment]
Hi @pabloduque0 !
Thanks for your message.
I'm sorry, this PR is my mistake. (I wanted to merge into my forked repository, but merged into the origin repository.)
So, please forget about this PR.

For your information, I have made this change for the following reason.
There was a phenomenon in which the optimization allocation results were almost unchanged from the starting_values in my MMM project. Therefore, we made this change to try running the optimization calculation with starting_value arbitrarily specified.

**Comment by pabloduque0** [comment]
Okay, let us know if you run into something that the underlying implementation might be causing so we can look at it.

**Comment by shuhoy** [comment]
@pabloduque0 
Of course! I will share any new findings with you.

**Pull request closed without merging**
